import fs from 'node:fs';
import path from 'node:path';
import { check } from './check.mjs';
import { loadBundle, posix, profile, toolDirectory, within } from './bundle.mjs';

export const marker = '<!-- Generated by project-okf-tools; edit concept metadata, then run index. -->';
const escape = value => String(value).replace(/\s+/g, ' ').replace(/[\\`*_[\]<>|]/g, '\\$&');
const encodePath = value => value.split('/').map(part => encodeURIComponent(part).replace(/[!'()*]/g, character => `%${character.charCodeAt(0).toString(16).toUpperCase()}`)).join('/');
const sorted = values => [...values].sort();

export function index(project) {
    const bundle = loadBundle(project);
    if (!bundle.config) throw new Error(bundle.diagnostics.map(d => d.message).join('\n'));
    const directories = new Set(['.']);
    for (const file of bundle.documents.keys()) {
        let directory = path.posix.dirname(file);
        while (directory !== '.') { directories.add(directory); directory = path.posix.dirname(directory); }
    }
    const writes = [];
    for (const directory of sorted(directories)) {
        const relative = path.posix.join(directory, 'index.md');
        const existing = bundle.documents.get(relative);
        if (existing && !existing.body.startsWith(`${marker}\n`)) throw new Error(`Preserving handwritten ${relative}; maintain it manually or explicitly replace it with a generated index.`);
        const lines = [];
        if (directory === '.') lines.push('---', `okf_version: "${profile.okfVersion}"`, '---');
        lines.push(marker, '', `# ${directory === '.' ? 'Documentation' : escape(path.posix.basename(directory))}`, '');
        for (const file of sorted(bundle.documents.keys())) {
            const base = path.posix.basename(file);
            if (path.posix.dirname(file) !== directory || ['index.md', 'log.md'].includes(base)) continue;
            const doc = bundle.documents.get(file);
            const title = doc.metadata?.title || base.replace(/\.md$/, '');
            const description = doc.metadata?.description || 'Legacy documentation awaiting review.';
            lines.push(`- [${escape(title)}](${encodePath(base)}) - ${escape(description)}`);
        }
        for (const child of sorted(directories)) {
            if (child === '.' || path.posix.dirname(child) !== directory) continue;
            const name = path.posix.basename(child);
            lines.push(`- [${escape(name)}](${encodePath(name)}/index.md) - ${escape(name)} documentation.`);
        }
        lines.push('');
        writes.push({ relative, file: path.join(bundle.root, relative), content: lines.join('\n') });
    }
    const proposedDocuments = new Map(writes.map(item => [item.relative, item.content]));
    const errors = check(project, { proposedDocuments }).filter(d => d.severity === 'error');
    if (errors.length) throw new Error(errors.map(d => `${d.file}: ${d.message}`).join('\n'));
    let changed = 0;
    for (const item of writes) {
        if (fs.existsSync(item.file) && fs.readFileSync(item.file, 'utf8') === item.content) continue;
        fs.writeFileSync(item.file, item.content);
        changed++;
    }
    return changed;
}

const runtimeFiles = ['bundle.mjs', 'check.mjs', 'scaffold.mjs', 'cli.mjs', 'profile.json', 'profile.md', 'package.json', 'package-lock.json'];

function safeDestination(project, relative) {
    const absolute = path.resolve(project, relative);
    if (!within(project, absolute)) throw new Error(`Destination escapes project: ${relative}`);
    let current = absolute;
    while (current !== project) {
        const stat = fs.lstatSync(current, { throwIfNoEntry: false });
        if (stat?.isSymbolicLink()) throw new Error(`Destination contains a symlink: ${relative}`);
        if (current !== absolute && stat && !stat.isDirectory()) throw new Error(`Destination parent is not a directory: ${relative}`);
        current = path.dirname(current);
    }
    return absolute;
}

export function init(project) {
    project = fs.realpathSync(project);
    // Existing docs require a deliberate migration, not a partial automatic rewrite.
    for (const relative of ['.okf.json', '.okf', 'docs', '.github/workflows/okf.yml']) {
        const absolute = safeDestination(project, relative);
        const stat = fs.lstatSync(absolute, { throwIfNoEntry: false });
        if (stat && !(relative === 'docs' && stat.isDirectory() && fs.readdirSync(absolute).length === 0)) throw new Error(`Preserving existing ${relative}; initialize a fresh project or follow the migration procedure.`);
    }
    const files = new Map();
    files.set('.okf.json', `${JSON.stringify({ profile: profile.profile, bundle: 'docs', legacy: {}, missingLinks: {} }, null, 2)}\n`);
    files.set('.okf/.gitignore', 'tools/node_modules/\n');
    files.set('docs/overview.md', '---\ntype: Reference\ntitle: Project documentation\ndescription: Entry point for maintained project knowledge.\nstatus: draft\n---\n# Project documentation\n\nDescribe the project purpose, supported usage and links to its architecture and\nrunbooks. Replace this starter with project-specific facts before marking it stable.\n');
    files.set('docs/index.md', `---\nokf_version: "${profile.okfVersion}"\n---\n${marker}\n\n# Documentation\n\n- [Project documentation](overview.md) - Entry point for maintained project knowledge.\n`);
    files.set('.github/workflows/okf.yml', `name: Documentation\n\non:\n  push:\n  pull_request:\n\npermissions:\n  contents: read\n\njobs:\n  okf:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm ci --prefix .okf/tools --ignore-scripts --no-audit --no-fund\n      - run: node .okf/tools/cli.mjs check .\n`);
    for (const file of runtimeFiles) files.set(`.okf/tools/${file}`, fs.readFileSync(path.join(toolDirectory, file)));
    // Read every source and validate every destination before the first write.
    for (const relative of files.keys()) {
        const absolute = safeDestination(project, relative);
        if (fs.existsSync(absolute)) throw new Error(`Preserving existing ${relative}.`);
    }
    for (const [relative, content] of files) {
        const destination = path.join(project, relative);
        fs.mkdirSync(path.dirname(destination), { recursive: true });
        fs.writeFileSync(destination, content, { flag: 'wx' });
    }
    return files.size;
}

function countMarkdown(directory) {
    if (!fs.existsSync(directory) || fs.lstatSync(directory).isSymbolicLink()) return 0;
    let count = 0;
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
        if (entry.isSymbolicLink()) continue;
        if (entry.isDirectory() && !['node_modules', '.git'].includes(entry.name)) count += countMarkdown(path.join(directory, entry.name));
        else if (entry.isFile() && entry.name.endsWith('.md') && !['index.md', 'log.md'].includes(entry.name)) count++;
    }
    return count;
}

export function inventory(workspace) {
    const projects = [];
    for (const entry of fs.readdirSync(workspace, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
        if (!entry.isDirectory() || entry.name.startsWith('.')) continue;
        const project = path.join(workspace, entry.name);
        if (!fs.existsSync(path.join(project, '.git'))) continue;
        const item = { name: entry.name, path: posix(path.resolve(project)), adoption: 'not-started', documents: countMarkdown(path.join(project, 'docs')), errors: 0, warnings: 0 };
        if (fs.existsSync(path.join(project, '.okf.json'))) {
            try {
                const bundle = loadBundle(project);
                const diagnostics = check(project);
                item.documents = [...bundle.documents.keys()].filter(f => !['index.md', 'log.md'].includes(path.posix.basename(f))).length;
                item.errors = diagnostics.filter(d => d.severity === 'error').length;
                item.warnings = diagnostics.filter(d => d.severity === 'warning').length;
                item.adoption = item.errors ? 'invalid' : Object.keys(bundle.config?.legacy || {}).length ? 'migrating' : 'adopted';
            } catch (error) { item.adoption = 'invalid'; item.errors = 1; item.problem = error.message; }
        }
        projects.push(item);
    }
    return projects;
}
